sudo: false

language: perl

perl:
    - "5.26"
    - "5.26-dbg"
    - "5.24"
    - "5.24-dbg"
    - "5.22"
    - "5.22-dbg"
    - "5.20"
    - "5.20-dbg"
    - "5.18"
    - "5.18-dbg"
    - "5.16"
    - "5.16-dbg"
    - "5.14"
    - "5.14-dbg"
    - "5.12"
    - "5.12-dbg"
    - "5.10"
    - "5.10-dbg"
    - "5.8"
    - "5.8-dbg"

before_install:
      - eval $(curl https://travis-perl.github.io/init) --auto

install:
    - cpanm --installdeps .

script:
    - RELEASE_TESTING=1 AUTHOR_TESTING=1 make test
